add_newline = false

[line_break]
disabled = true

[aws]
style = "bold #ffb86c"

# Î»
[character]
error_symbol = "[ðŸ‘Ž](bold #ff5555)"
success_symbol = "[ðŸ”¥](bold #ffb86c)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #bd93f9"

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"

[package]
disabled = true


[cmake]
format = "via [$symbol]($style)"
disabled = true

[cobol]
format = "via [$symbol]($style)"
disabled = true

[crystal]
format = "via [$symbol]($style)"
disabled = true

[dart]
format = "via [$symbol]($style)"
disabled = true

[deno]
format = "via [$symbol]($style)"
disabled = true

[dotnet]
format = "[$symbol(ðŸŽ¯ $tfm )]($style)"
disabled = true

[elixir]
format = 'via [$symbol]($style)'
disabled = true

[elm]
format = 'via [$symbol]($style)'
disabled = true

[erlang]
format = 'via [$symbol]($style)'
disabled = true

[golang]
format = 'via [$symbol]($style)'
disabled = true

[helm]
format = 'via [$symbol]($style)'
disabled = true

[julia]
format = 'via [$symbol]($style)'
disabled = true

[kotlin]
format = 'via [$symbol]($style)'
disabled = true

[lua]
format = 'via [$symbol]($style)'
disabled = true

[nim]
format = 'via [$symbol]($style)'
disabled = true

[nodejs]
format = 'via [$symbol]($style)'
disabled = true

[ocaml]
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'
disabled = true

[perl]
format = 'via [$symbol]($style)'
disabled = true

[php]
format = 'via [$symbol]($style)'
disabled = true

[pulumi]
format = 'via [$symbol$stack]($style)'
disabled = true

[purescript]
format = 'via [$symbol]($style)'
disabled = true

[python]
format = 'via [$symbol]($style)'
disabled = true

[red]
format = 'via [$symbol]($style)'
disabled = true

[rlang]
format = 'via [$symbol]($style)'
disabled = true

[ruby]
format = 'via [$symbol]($style)'
disabled = true

[rust]
format = 'via [$symbol]($style)'
disabled = true

[swift]
format = 'via [$symbol]($style)'
disabled = true

[vagrant]
format = 'via [$symbol]($style)'
disabled = true

[vlang]
format = 'via [$symbol]($style)'
disabled = true

[zig]
format = 'via [$symbol]($style)'
disabled = true
